import { execFileSync } from 'node:child_process';
import { existsSync, readdirSync } from 'node:fs';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { parseDeck, type Deck, type SlideElement } from '../src/shared/deck.js';
import { importPowerPoint } from '../src/main/pptxImport.js';
import { loadDeck, loadTheme } from '../src/main/deckStore.js';

/**
 * PowerPoint import regression tests.
 *
 * `test/fixtures/pptx/reference.pptx` is generated by `make_reference.py` with
 * python-pptx, so every position in it is known: the slide is 16:9 at 13.333
 * inches wide, which maps to the 1920px canvas at 144px per inch and 2px per
 * point. The assertions below are those numbers.
 *
 * Point PPTX_FIXTURES at a folder of real .pptx decks to run the corpus check
 * as well; it skips itself when the folder is absent so a fresh checkout passes.
 */

const PYTHON = existsSync(join(process.cwd(), '.venv-import/bin/python'))
  ? join(process.cwd(), '.venv-import/bin/python')
  : 'python3';

const REFERENCE = join(process.cwd(), 'test/fixtures/pptx/reference.pptx');
const FIXTURES = process.env.PPTX_FIXTURES;
const LOCAL_FIXTURES = join(process.cwd(), 'example_presentations');

const IN = 144;

function analyse(pptxPath: string): { deck: Deck; report: { slides: number; elements: number; unsupported: Record<string, number>; warnings: string[] } } {
  const stdout = execFileSync(PYTHON, ['-c', [
    'import json, sys',
    'from pathlib import Path',
    'sys.path.insert(0, "importers/pptx")',
    'from import_pptx import import_pptx',
    "deck, report = import_pptx(Path(sys.argv[1]), Path('/dev/null'), False)",
    'print(json.dumps({"deck": deck, "report": report.to_dict()}))',
  ].join('\n'), pptxPath], { encoding: 'utf8', cwd: process.cwd(), maxBuffer: 64 * 1024 * 1024 });
  const payload = JSON.parse(stdout) as { deck: unknown; report: { slides: number; elements: number; unsupported: Record<string, number>; warnings: string[] } };
  return { deck: parseDeck(payload.deck), report: payload.report };
}

function shape(deck: Deck, slide: number, predicate: (el: SlideElement) => boolean): SlideElement {
  const found = deck.slides[slide].elements.find(predicate);
  if (!found) throw new Error(`no matching element on slide ${slide + 1}`);
  return found;
}

describe.skipIf(!existsSync(REFERENCE))('powerpoint importer', () => {
  let cached: ReturnType<typeof analyse> | null = null;
  const reference = () => (cached ??= analyse(REFERENCE));

  it('maps the 16:9 slide onto the 1920x1080 canvas with nothing unsupported', () => {
    const { deck, report } = reference();
    expect(deck.canvas).toEqual({ w: 1920, h: 1080 });
    expect(deck.slides).toHaveLength(5);
    expect(report.unsupported).toEqual({});
    // Master placeholders (prompt text, date, slide number) never leak onto slides.
    for (const slide of deck.slides) {
      for (const el of slide.elements) {
        if (el.type === 'text') expect(el.html).not.toContain('Click to edit');
      }
    }
  });

  it('places plain shapes exactly where PowerPoint had them', () => {
    const { deck } = reference();
    const red = shape(deck, 1, (el) => el.type === 'shape' && el.fill === '#ff0000');
    expect([red.x, red.y, red.w, red.h, red.rot]).toEqual([IN, IN, 3 * IN, 2 * IN, 0]);
    if (red.type !== 'shape') throw new Error('expected a shape');
    expect(red.shape).toBe('rect');
    expect(red.stroke).toBeNull();

    const blue = shape(deck, 1, (el) => el.type === 'shape' && el.fill === '#0000ff');
    if (blue.type !== 'shape') throw new Error('expected a shape');
    expect([blue.x, blue.y, blue.w, blue.h]).toEqual([5 * IN, IN, 2 * IN, 2 * IN]);
    expect(blue.shape).toBe('ellipse');
    expect(blue.stroke).toBe('#000000');
    expect(blue.strokeWidth).toBe(6); // 3pt

    const green = shape(deck, 1, (el) => el.type === 'shape' && el.fill === '#008000');
    expect(green.rot).toBe(30);

    const grey = shape(deck, 1, (el) => el.type === 'shape' && el.fill === '#808080');
    if (grey.type !== 'shape') throw new Error('expected a shape');
    expect(grey.shape).toBe('rect');
    expect(grey.radius).toBeCloseTo(0.16667 * IN, 0);

    const triangle = shape(deck, 1, (el) => el.type === 'shape' && el.fill === '#ffa500');
    if (triangle.type !== 'shape') throw new Error('expected a shape');
    expect(triangle.shape).toBe('path');
    expect(triangle.path).toBe('M 144.00 0.00 L 288.00 288.00 L 0.00 288.00 Z');
    expect(triangle.pathSize).toEqual({ w: 2 * IN, h: 2 * IN });
  });

  it('turns a straight connector into a native arrow between its endpoints', () => {
    const { deck } = reference();
    const arrow = shape(deck, 1, (el) => el.type === 'shape' && el.shape === 'arrow');
    if (arrow.type !== 'shape') throw new Error('expected a shape');
    // From (7in, 4in) to (10in, 6in): a 3x2 inch diagonal.
    expect(arrow.w).toBeCloseTo(Math.hypot(3 * IN, 2 * IN), 1);
    expect(arrow.rot).toBeCloseTo((Math.atan2(2, 3) * 180) / Math.PI, 1);
    expect(arrow.x + arrow.w / 2).toBeCloseTo(8.5 * IN, 1);
    expect(arrow.y + arrow.h / 2).toBeCloseTo(5 * IN, 1);
    expect(arrow.arrowEnd).toBe(true);
    expect(arrow.arrowStart).toBe(false);
    expect(arrow.strokeWidth).toBe(4); // 2pt
  });

  it('keeps run-level styling as spans against the box style', () => {
    const { deck } = reference();
    const hello = shape(deck, 1, (el) => el.type === 'text' && el.html.startsWith('Hello'));
    if (hello.type !== 'text') throw new Error('expected text');
    expect([hello.x, hello.y, hello.w, hello.h]).toEqual([8 * IN, 0.25 * IN, 4 * IN, 0.5 * IN]);
    expect(hello.style['font-size']).toBe('48px'); // 24pt
    expect(hello.style['font-weight']).toBe('700');
    expect(hello.style.color).toBe('#123456');
    expect(hello.html).toBe('Hello <span style="font-style: italic">world</span>');
    expect(deck.slides[1].notes).toBe('Speaker notes for slide two.');
  });

  it('escapes the quotes a run\'s font family carries inside its style attribute', () => {
    // Unescaped, `style="font-family: "Calibri", …"` ends at the first quote
    // and the run loses its face and everything listed after it.
    const stdout = execFileSync(PYTHON, ['-c', [
      'from importers.pptx.import_pptx import _style_attr',
      "print(_style_attr({'font-family': '\"Calibri\", \"Carlito\", sans-serif', 'font-weight': '700'}))",
    ].join('\n')], { encoding: 'utf8', cwd: process.cwd() });
    expect(stdout.trim()).toBe('style="font-family: &quot;Calibri&quot;, &quot;Carlito&quot;, sans-serif; font-weight: 700"');
  });

  it('inherits placeholder geometry and type from the layout and master', () => {
    const { deck } = reference();
    const title = shape(deck, 0, (el) => el.type === 'text' && el.html === 'Reference deck');
    expect(title.class).toContain('role-title');
    // python-pptx's default title placeholder: 44pt, centred, vertically centred.
    if (title.type !== 'text') throw new Error('expected text');
    expect(title.style['font-size']).toBe('88px');
    expect(title.align).toBe('center');
    expect(title.valign).toBe('middle');
    expect(title.w).toBeGreaterThan(1000);

    const subtitle = shape(deck, 0, (el) => el.type === 'text' && el.html.startsWith('Known geometry'));
    expect(subtitle.class).toContain('role-body');
  });

  it('imports pictures with crops expressed as a source box', () => {
    const { deck } = reference();
    const images = deck.slides[2].elements.filter((el) => el.type === 'image');
    expect(images).toHaveLength(2);
    const [plain, cropped] = images;
    if (plain.type !== 'image' || cropped.type !== 'image') throw new Error('expected images');
    expect([plain.x, plain.y, plain.w, plain.h]).toEqual([IN, IN, 4 * IN, 2 * IN]);
    expect(plain.sourceBox).toBeNull();
    // The visible window is the shape; 25% cropped off each side means the
    // whole picture is twice as wide and starts a quarter of it to the left.
    expect([cropped.x, cropped.y, cropped.w, cropped.h]).toEqual([6 * IN, IN, 2 * IN, 2 * IN]);
    expect(cropped.sourceBox).toEqual({ x: -IN, y: -0, w: 4 * IN, h: 2 * IN });
  });

  it('flattens groups through their child coordinate space', () => {
    const { deck } = reference();
    const cyan = shape(deck, 2, (el) => el.type === 'shape' && el.fill === '#00ffff');
    const magenta = shape(deck, 2, (el) => el.type === 'shape' && el.fill === '#ff00ff');
    // The group maps a 3x2 inch child extent at (1in, 4in) onto 1.5x1 inch at (6in, 4in).
    expect([cyan.x, cyan.y, cyan.w, cyan.h]).toEqual([6 * IN, 4 * IN, 0.5 * IN, 0.5 * IN]);
    expect([magenta.x, magenta.y, magenta.w, magenta.h]).toEqual([7 * IN, 4.5 * IN, 0.5 * IN, 0.5 * IN]);
  });

  it('turns bulleted body text into nested lists and tables into table objects', () => {
    const { deck } = reference();
    const body = shape(deck, 3, (el) => el.type === 'text' && el.html.includes('First point'));
    if (body.type !== 'text') throw new Error('expected text');
    expect(body.class).toContain('role-body');
    expect(body.html).toBe(
      '<ul><li>First point<ul><li><span style="font-size: 56px">Nested point</span></li></ul></li><li>Second point</li></ul>',
    );

    const table = shape(deck, 3, (el) => el.type === 'text' && Boolean(el.table));
    if (table.type !== 'text') throw new Error('expected text');
    expect([table.x, table.y, table.w]).toEqual([7 * IN, 4 * IN, 4 * IN]);
    expect(table.table?.columnWidths).toEqual([2 * IN, 2 * IN]);
    expect(table.html).toContain('<td');
    expect(table.html).toContain('B2');
  });

  it('keeps hidden slides but marks them skipped', () => {
    const { deck } = reference();
    expect(deck.slides[4].skipped).toBe(true);
    expect(deck.slides.slice(0, 4).every((slide) => !slide.skipped)).toBe(true);
  });

  it('imports through the app wrapper with streaming progress and reopens from disk', async () => {
    const out = await mkdtemp(join(tmpdir(), 'pptx-open-smoke-'));
    try {
      const phases: { message: string; ratio: number | null }[] = [];
      const imported = await importPowerPoint(REFERENCE, out, (message, ratio) => phases.push({ message, ratio }));
      expect(imported.dir).toBe(out);
      expect(imported.deck.slides).toHaveLength(5);
      expect(phases.some((p) => /^Converting slide \d+ of \d+$/.test(p.message))).toBe(true);
      expect(phases.some((p) => p.message.includes('deck.json'))).toBe(true);
      const ratios = phases.map((p) => p.ratio).filter((r): r is number => r !== null);
      expect(ratios).toEqual([...ratios].sort((a, b) => a - b));
      expect(ratios.at(-1)).toBe(1);

      const opened = await loadDeck(out);
      expect(opened).toEqual(imported.deck);
      expect((await loadTheme(out, opened.theme)).length).toBeGreaterThan(0);
      for (const slide of opened.slides) {
        for (const el of slide.elements) {
          if (el.type === 'image' || el.type === 'video') {
            expect(existsSync(join(out, el.src)), `missing ${el.src}`).toBe(true);
          }
        }
      }
    } finally {
      await rm(out, { recursive: true, force: true });
    }
  }, 60_000);

  const fixtures = FIXTURES && existsSync(FIXTURES)
    ? FIXTURES
    : existsSync(LOCAL_FIXTURES) ? LOCAL_FIXTURES : null;
  const corpus = fixtures
    ? readdirSync(fixtures).filter((f) => f.endsWith('.pptx') && !f.startsWith('~$')).map((f) => join(fixtures, f))
    : [];

  it.skipIf(corpus.length === 0)('imports every corpus deck without failing', () => {
    for (const deckPath of corpus) {
      const { deck, report } = analyse(deckPath);
      expect(report.slides, `${deckPath} produced no slides`).toBeGreaterThan(0);
      const skipped = Object.values(report.unsupported).reduce((a, b) => a + b, 0);
      expect(skipped / Math.max(1, report.elements)).toBeLessThan(0.25);
      for (const slide of deck.slides) {
        for (const el of slide.elements) {
          expect(Number.isFinite(el.x) && Number.isFinite(el.y)).toBe(true);
          expect(el.w).toBeGreaterThan(0);
          expect(el.h).toBeGreaterThan(0);
        }
      }
    }
  }, 600_000);
});
