import { existsSync } from 'node:fs';
import { readFile, rename, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import deckBrief from '../../docs/deck-brief.md?raw';

/**
 * The agent brief every deck folder carries.
 *
 * Agent CLIs read `AGENTS.md` from their working directory, and when someone
 * points an agent at a talk that directory is the deck — not this repository,
 * where the real guide lives. So the editor writes the deck-facing guide into
 * the folder whenever it attaches a deck to a window: open, create, import,
 * Save As, or a folder passed on the command line all pass through one place.
 *
 * The text is `docs/deck-brief.md`, bundled into the main process at build
 * time so a packaged app carries it without shipping the docs folder. It
 * stays a document in the repository so it can be read and reviewed as prose.
 *
 * Regeneration keeps the brief current with the installed editor: the file is
 * rewritten whenever its content would change, *unless* the author has taken
 * it over. Ownership is signalled by removing the generated-marker line at the
 * top; a file without it is never touched again, so notes about the talk that
 * someone typed into it are safe.
 */

export const AGENT_GUIDE_FILE = 'AGENTS.md';

/**
 * First line of every generated brief. Its presence is what allows the editor
 * to rewrite the file; the brief tells the reader so in plain words.
 */
export const AGENT_GUIDE_MARKER = '<!-- generated by DeckWerk; delete this line to stop it being rewritten -->';

export interface AgentGuideOptions {
  /** Absolute path of the `slide-agent` launcher, when this installation has one. */
  launcher?: string | null;
  /** A complete replacement for the "Finding the CLI" section (mirrors ship their own tool). */
  launcherHint?: string;
}

/**
 * Where the CLI lives for the running editor.
 *
 * From a checkout — `electron-vite dev` or `out/main` — the launcher sits at
 * `bin/slide-agent` two levels up from this module. A packaged app does not
 * ship the dev CLI, so the path is offered only when it is real.
 */
export function defaultLauncherPath(): string | null {
  try {
    const launcher = fileURLToPath(new URL('../../bin/slide-agent', import.meta.url));
    return existsSync(launcher) ? launcher : null;
  } catch {
    return null;
  }
}

/** The exact text of the brief for this installation. */
export function renderAgentGuide(options: AgentGuideOptions = {}): string {
  const hint = options.launcher
    ? `
## Finding the CLI

\`slide-agent\` is a command from the DeckWerk checkout. If it is not on your
PATH, run it by its full path — this installation's copy is at:

    ${options.launcher}

or symlink it once: \`ln -s ${shellQuote(options.launcher)} ~/bin/slide-agent\`.
`
    : `
## Finding the CLI

\`slide-agent\` is a command from the DeckWerk source checkout; the packaged
app does not bundle it. Clone https://github.com/vsitzmann/deckwerk, run
\`npm install\`, and symlink \`bin/slide-agent\` somewhere on your PATH. It
works against this folder whether or not the editor is running.
`;
  const body = deckBrief.replace('{{LAUNCHER_HINT}}', options.launcherHint ?? hint);
  return `${AGENT_GUIDE_MARKER}\n${body.endsWith('\n') ? body : `${body}\n`}`;
}

export type AgentGuideOutcome = 'written' | 'unchanged' | 'owned';

/**
 * Bring the deck folder's `AGENTS.md` up to date.
 *
 * Returns what happened: `written` when the file was created or refreshed,
 * `unchanged` when it already matched, and `owned` when the author has removed
 * the marker and the file was left alone. Writes are atomic — an agent may be
 * reading the file at the moment the deck opens.
 */
export async function writeAgentGuide(
  dir: string,
  options: AgentGuideOptions = {},
): Promise<AgentGuideOutcome> {
  const path = join(dir, AGENT_GUIDE_FILE);
  const next = renderAgentGuide(options);
  if (existsSync(path)) {
    const current = await readFile(path, 'utf8');
    if (!current.startsWith(AGENT_GUIDE_MARKER)) return 'owned';
    if (current === next) return 'unchanged';
  }
  const temporary = `${path}.${process.pid}.tmp`;
  await writeFile(temporary, next, 'utf8');
  await rename(temporary, path);
  return 'written';
}

function shellQuote(path: string): string {
  return /^[A-Za-z0-9_/.@:+=-]+$/.test(path) ? path : `'${path.replace(/'/g, `'\\''`)}'`;
}
